import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
    products: [
      {
        _id: '1',
        name: 'Blueberries',
        category: 'Fruit',
        image: '/images/p1.jpg',
        price: 10,
        countInStock: 10,
        zipcode: '78749',
        rating: 4.5,
        numReviews: 10,
        description: 'The freshest blueberries this side of the Mississippi',
      },
      {
        _id: '2',
        name: 'Oranges',
        category: 'Fruit',
        image: '/images/p2.jpg',
        price: 12,
        countInStock: 12,
        zipcode: '78748',
        rating: 4.0,
        numReviews: 12,
        description: 'Mouth watering oranges',
      },
      {
        _id: '3',
        name: 'Limes',
        category: 'Fruit',
        image: '/images/p3.jpg',
        price: 9,
        countInStock: 0,
        zipcode: '78749',
        rating: 4.8,
        numReviews: 17,
        description: 'Delightful limes',
      },
      {
        _id: '4',
        name: 'Watermelon',
        category: 'Fruit',
        image: '/images/p4.jpg',
        price: 6,
        countInStock: 20,
        zipcode: '78704',
        rating: 4.5,
        numReviews: 14,
        description: 'The perfect watermelon for you next party',
      },
      {
        _id: '5',
        name: 'Lettuce',
        category: 'Vegetable',
        image: '/images/p5.jpg',
        price: 5,
        countInStock: 18,
        zipcode: '78744',
        rating: 4.5,
        numReviews: 10,
        description: 'Fresh lettuce',
      },
      {
        _id: '6',
        name: 'Pears',
        category: 'Fruit',
        image: '/images/p6.jpg',
        price: 7,
        countInStock: 11,
        zipcode: '78717',
        rating: 4.5,
        numReviews: 15,
        description: 'Perfect pears',
      },
    ],
  };
  export default data;