const data = {
    products: [
      {
        _id: '1',
        name: 'Blueberries',
        category: 'Fruit',
        image: '/images/p1.jpg',
        price: 10,
        zipcode: '78749',
        rating: 4.5,
        numReviews: 10,
        description: 'The freshest blueberries this side of the Mississippi',
      },
      {
        _id: '2',
        name: 'Oranges',
        category: 'Fruit',
        image: '/images/p2.jpg',
        price: 12,
        zipcode: '78748',
        rating: 4.0,
        numReviews: 12,
        description: 'Mouth watering oranges',
      },
      {
        _id: '3',
        name: 'Limes',
        category: 'Fruit',
        image: '/images/p3.jpg',
        price: 9,
        zipcode: '78749',
        rating: 4.8,
        numReviews: 17,
        description: 'Delightful limes',
      },
      {
        _id: '4',
        name: 'Watermelon',
        category: 'Fruit',
        image: '/images/p4.jpg',
        price: 6,
        zipcode: '78704',
        rating: 4.5,
        numReviews: 14,
        description: 'The perfect watermelon for you next party',
      },
      {
        _id: '5',
        name: 'Lettuce',
        category: 'Vegetable',
        image: '/images/p5.jpg',
        price: 5,
        zipcode: '78744',
        rating: 4.5,
        numReviews: 10,
        description: 'Fresh lettuce',
      },
      {
        _id: '6',
        name: 'Pears',
        category: 'Fruit',
        image: '/images/p6.jpg',
        price: 7,
        zipcode: '78717',
        rating: 4.5,
        numReviews: 15,
        description: 'Perfect pears',
      },
    ],
  };
  export default data;